data_dir_name: 'data'
data_file_name: 'gravity_vector_data.json'
do_early_stopping: false
do_save_model: true
early_stopping_patience: 500
max_layers: 10
is_funnel_shaped: true
initial_layers: [16, 32, 16]

training_settings:     
    batch_size: 32000    
    epochs: 6000         
    verbose: 0      

