plot_setups = {
    "Fuel to reach target":                                     {"data_key":"fuel_to_5p_to_target",         "label": "Fuel", "min": 16000, "max": 32000},
    "Fuel":                                                     {"data_key":"fuel",                         "label": "Fuel", "min": 16000, "max": 32000},
    "Fuel to reach and stay at target":                         {"data_key":"fuel_for_at_target_at_end",    "label": "Fuel", "min": 16000, "max": 32000},
    "Ratio of minimum distance and initial distance to target": {"data_key":"min_start_cost_ratio",         "label": "Ratio", "min": 0, "max": 1},
    "Likelihood of last distance to target greater than first": {"data_key":"ends_further_than_start",      "label": "Likelihood", "min": 0, "max": 1},
    "Likelihood of reaching target":                            {"data_key":"reaches_target",               "label": "Likelihood", "min": 0, "max": 1},
    "Likelihood of collision":                                  {"data_key":"collisions",                   "label": "Likelihood", "min": 0,  "max": 1},
    "Likelihood of staying at Target":                          {"data_key":"stays_at_target",              "label": "Likelihood", "min": 0,  "max": 1},
    "Time of neural network computations":                      {"data_key":"agent_time",                   "label": "Time [s]", "min": 0,  "max": 0.002, "unwanted_models": ["GCPD"]},
    "Time of GCPD computations":                                {"data_key":"gcpd_time",                    "label": "Time [s]", "min": 0,  "max": 0.002},
    "Time of overhead computations":                            {"data_key":"overhead_time",                "label": "Time [s]", "min": 0,  "max": 0.002},
    "Cost given as final distance to target":                   {"data_key":"end_cost",                     "label": "Cost", "min": 0,  "max": 151000},
    "Cost given as final distance to target (508R removed)":    {"data_key":"end_cost",                     "label": "Cost", "min": 0,  "max": 25000,   "unwanted_models": ["508R"]},
    "Cost given as minimum distance to target":                 {"data_key":"min_cost",                     "label": "Cost", "min": 0,  "max": 150},
    "Time to reach target":                                     {"data_key":"time_to_5p_to_target",         "label": "Time", "min": 0,  "max": 25},
    "Mean squared error (168S removed)":                        {"data_key":"acc_se",                       "label": "Error", "min": 0,  "max": 200,    "unwanted_models": ["GCPD", "168S"]},
    "Mean squared error":                                       {"data_key":"acc_se",                       "label": "Error", "min": 0,  "max": 20000,  "unwanted_models": ["GCPD"]},
    "Mean absolute error":                                      {"data_key":"acc_ae",                       "label": "Error", "min": 0,  "max": 7,      "unwanted_models": ["GCPD"]},
    "Mean squared error of capped acceleration":                {"data_key":"capped_acc_se",                "label": "Error", "min": 0,  "max": 22,     "unwanted_models": ["GCPD"]},
    "Mean absolute error of capped acceleration":               {"data_key":"capped_acc_ae",                "label": "Error", "min": 0,  "max": 7,      "unwanted_models": ["GCPD"]},
    "Length of gravitatial vector":                             {"data_key":"grav_length",                  "label": "Gravitational acceleration", "min": 0,  "max": 40},
    "Length of gravitational vector for reaching target":       {"data_key":"grav_length_reach_target",     "label": "Gravitational acceleration", "min": 0,  "max": 40},
    "Length of gravitational vector for staying at target":     {"data_key":"grav_length_stay_at_target",   "label": "Gravitational acceleration", "min": 0,  "max": 40},
    "Maximum gravitational acceleration":                       {"data_key":"max_grav",                     "label": "Gravitational acceleration", "min": 0,  "max": 11000},
    "Maximum gravitational acceleration for staying at target": {"data_key":"max_grav_stays_at_target",     "label": "Gravitational acceleration", "min": 0,  "max": 2500}
}