sim: 
    run:
        execution_mode:  'normal' # infinite, normal, simple_data_gen
        batch_size: 2 # is only used if do_infinite_run is True

    sim_time: 30
    num_of_data_points: 30
    num_of_iterations: 1

    # For randomly generating positions, velocities, etc. of bodies   
    config_generation: 
        max_pos_radius: 1000
        max_vel_radius: 50
        min_dist_to_target: 200
        num_of_planets: 0

    bodies: 
        use_fixed_setup: False # disables config_generation 
        agent: 
            agent_type: 'nn_nop' # provide a value from enum AgentType
            nn_model_path: 'saved_models/no_planet_128_32_8'
            index: 0
            target_pos: (100, 100, 0) # not used now, should be setup to be used if use_fixed_setup = True 
            max_acceleration: 10
            mass: 500
            radius: 0.01
            scale_policy:
                preferred_value: 1
                invalid_value: -1
        planets:
            mass: 1e10
            radius: 5

data:
    write_data_to_files: False # This should be set to False when using nn_agent
    dir_name: data
    dir_analytical_agent: analytical_agent
    dir_gcpd_agent: gcpd_agent
    dir_nn_agent: nn_agent
    dir_bin: bin
    dir_json: json
    file_extensions:
        bin: ".bin"
        json: ".json"

logging:
    info_str:
        separator: ','
